export default {
  base: {
    name: "基础",
    children: [
      {
        title: "bookSourceType",
        id: "bookSourceType",
        type: "Array",
        array: ["văn bản", "âm thanh", "hình ảnh", "tài liệu"],
        required: true,
      },
      {
        title: "bookSourceUrl",
        id: "bookSourceUrl",
        type: "String",
        hint: "Thông thường điền vào trang chủ của website, ví dụ: https://www.qidian.com",
        required: true,
      },
      {
        title: "bookSourceName",
        id: "bookSourceName",
        type: "String",
        hint: "sẽ xuất hiện trong danh sách nguồn",
        required: true,
      },
      {
        title: "bookSourceGroup",
        id: "bookSourceGroup",
        type: "String",
        hint: "đặc trưng thông tin mô tả nguồn",
      },
      {
        title: "bookSourceComment",
        id: "bookSourceComment",
        type: "String",
        hint: "Mô tả nguồn tác giả và trạng thái",
      },
      {
        title: "variableComment",
        id: "variableComment",
        type: "String",
        hint: "Mô tả biến nguồn sách",
      },
      {
        title: "loginUrl",
        id: "loginUrl",
        type: "String",
        hint: "Điền URL đăng nhập trang web, chỉ hữu ích cho các nguồn yêu cầu đăng nhập",
      },
      {
        title: "loginUi",
        id: "loginUi",
        type: "String",
        hint: "Tùy chỉnh màn hình đăng nhập",
      },
      {
        title: "loginCheckJs",
        id: "loginCheckJs",
        type: "String",
        hint: "js phát hiện đăng nhập",
      },
      {
        title: "coverDecodeJs",
        id: "coverDecodeJs",
        type: "String",
        hint: "giải mã bìa js",
      },
      {
        title: "concurrentRate",
        id: "concurrentRate",
        type: "String",
        hint: "Tỷ lệ đồng thời, chẳng hạn như 1000 (khoảng thời gian truy cập 1000 mili giây) hoặc 1/1000 (truy cập một lần trong vòng 1000 mili giây)",
      },
      {
        title: "jsLib",
        id: "jsLib",
        type: "String",
        hint: "js, bạn có thể điền js hoặc đối tượng khóa-giá trị để nhận các tệp js trực tuyến",
      },
      {
        title: "header",
        id: "header",
        type: "String",
        hint: "ID khách hàng",
      },
      {
        title: "bookUrlPattern",
        id: "bookUrlPattern",
        type: "String",
        hint: "Nó hợp lệ khi tên miền của url trang chi tiết khác với tên miền của url nguồn, được sử dụng để thêm URL",
      },
    ],
  },
  search: {
    name: "tìm kiếm",
    children: [
      {
        title: "searchUrl",
        id: "searchUrl",
        type: "String",
        hint: "[Có thể bỏ qua tên miền]/search.php@kw={{key}}",
      },
      {
        title: "checkKeyWord",
        namespace: "ruleSearch",
        id: "checkKeyWord",
        type: "String",
        hint: "Kiểm tra từ khóa, bạn nên điền vào",
      },
      {
        title: "bookList",
        namespace: "ruleSearch",
        id: "bookList",
        type: "String",
        hint: "Chọn nút sách (kết quả quy tắc là Danh sách<Phần tử>)",
      },
      {
        title: "name",
        namespace: "ruleSearch",
        id: "name",
        type: "String",
        hint: "Chọn tiêu đề sách nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "author",
        namespace: "ruleSearch",
        id: "author",
        type: "String",
        hint: "Chọn tác giả nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "kind",
        namespace: "ruleSearch",
        id: "kind",
        type: "String",
        hint: "Chọn thông tin phân loại nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "wordCount",
        namespace: "ruleSearch",
        id: "wordCount",
        type: "String",
        hint: "Chọn thông tin đếm từ của nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "lastChapter",
        namespace: "ruleSearch",
        id: "lastChapter",
        type: "String",
        hint: "Chọn chương mới nhất của nút (kết quả của quy tắc là Chuỗi)",
      },
      {
        title: "intro",
        namespace: "ruleSearch",
        id: "intro",
        type: "String",
        hint: "Chọn giới thiệu sách nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "coverUrl",
        namespace: "ruleSearch",
        id: "coverUrl",
        type: "String",
        hint: "Chọn bìa sách của nút (kết quả của quy tắc là url kiểu Chuỗi)",
      },
      {
        title: "bookUrl",
        namespace: "ruleSearch",
        id: "bookUrl",
        type: "String",
        hint: "Chọn URL của trang chi tiết sách (kết quả quy tắc là một URL có kiểu String)",
      },
    ],
  },
  find: {
    name: "Phát hiện",
    children: [
      {
        title: "exploreUrl",
        id: "exploreUrl",
        type: "String",
        hint: "Định dạng khám phá duy nhất <name>::<url> hoặc {url:<url>,title:<name>,style:...}; định dạng trước được kết nối bằng một dòng mới hoặc && và định dạng sau được đặt trong một mảng ; js có thể được sử dụng để tạo động",
      },
      {
        title: "exploreScreen",
        id: "exploreScreen",
        type: "String",
        hint: "Khám phá các quy tắc bộ lọc",
      },
      {
        title: "bookList",
        namespace: "ruleExplore",
        id: "bookList",
        type: "String",
        hint: "Chọn nút sách (kết quả quy tắc là Danh sách<Phần tử>)",
      },
      {
        title: "name",
        namespace: "ruleExplore",
        id: "name",
        type: "String",
        hint: "Chọn tiêu đề sách nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "author",
        namespace: "ruleExplore",
        id: "author",
        type: "String",
        hint: "Chọn tác giả nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "kind",
        namespace: "ruleExplore",
        id: "kind",
        type: "String",
        hint: "Chọn thông tin phân loại nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "wordCount",
        namespace: "ruleExplore",
        id: "wordCount",
        type: "String",
        hint: "Chọn thông tin đếm từ của nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "lastChapter",
        namespace: "ruleExplore",
        id: "lastChapter",
        type: "String",
        hint: "Chọn chương mới nhất của nút (kết quả của quy tắc là Chuỗi)",
      },
      {
        title: "intro",
        namespace: "ruleExplore",
        id: "intro",
        type: "String",
        hint: "Chọn giới thiệu sách nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "coverUrl",
        namespace: "ruleExplore",
        id: "coverUrl",
        type: "String",
        hint: "Chọn bìa sách của nút (kết quả của quy tắc là url kiểu Chuỗi)",
      },
      {
        title: "bookUrl",
        namespace: "ruleExplore",
        id: "bookUrl",
        type: "String",
        hint: "Chọn URL của trang chi tiết sách (kết quả quy tắc là một URL có kiểu String)",
      },
    ],
  },
  detail: {
    name: "chi tiết",
    children: [
      {
        title: "init",
        namespace: "ruleBookInfo",
        id: "init",
        type: "String",
        hint: "Được sử dụng để tăng tốc độ truy xuất thông tin chi tiết, chỉ hỗ trợ quy tắc tất cả trong một",
      },
      {
        title: "name",
        namespace: "ruleBookInfo",
        id: "name",
        type: "String",
        hint: "Chọn tiêu đề sách nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "author",
        namespace: "ruleBookInfo",
        id: "author",
        type: "String",
        hint: "Chọn tác giả nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "kind",
        namespace: "ruleBookInfo",
        id: "kind",
        type: "String",
        hint: "Chọn thông tin phân loại nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "wordCount",
        namespace: "ruleBookInfo",
        id: "wordCount",
        type: "String",
        hint: "Chọn thông tin đếm từ của nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "lastChapter",
        namespace: "ruleBookInfo",
        id: "lastChapter",
        type: "String",
        hint: "Chọn chương mới nhất của nút (kết quả của quy tắc là Chuỗi)",
      },
      {
        title: "intro",
        namespace: "ruleBookInfo",
        id: "intro",
        type: "String",
        hint: "Chọn giới thiệu sách nút (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "coverUrl",
        namespace: "ruleBookInfo",
        id: "coverUrl",
        type: "String",
        hint: "Chọn bìa sách của nút (kết quả của quy tắc là url kiểu Chuỗi)",
      },
      {
        title: "tocUrl",
        namespace: "ruleBookInfo",
        id: "tocUrl",
        type: "String",
        hint: "Chọn URL của trang chi tiết sách (kết quả quy tắc là URL kiểu String, có thể bỏ qua nếu trùng với trang chi tiết)",
      },
      {
        title: "downloadUrls",
        namespace: "ruleBookInfo",
        id: "downloadUrls",
        type: "String",
        hint: "URL tải xuống nguồn cho các tệp và sách (kết quả của quy tắc là một URL kiểu Chuỗi, nhiều liên kết trả về một mảng)",
      },
      {
        title: "canReName",
        namespace: "ruleBookInfo",
        id: "canReName",
        type: "String",
        hint: "Cho phép sửa tên tác giả của tên sách (kết quả của quy tắc là kiểu String, mặc định không được phép)",
      },
    ],
  },
  directory: {
    name: "Mục lục",
    children: [
      {
        title: "init",
        namespace: "ruleToc",
        id: "preUpdateJs",
        type: "String",
        hint: "Gọi JS trước khi cập nhật thư mục để cập nhật động liên kết thư mục",
      },
      {
        title: "chapterList",
        namespace: "ruleToc",
        id: "chapterList",
        type: "String",
        hint: "Chọn nút chương của mục lục (kết quả của luật là List<Element>)",
      },
      {
        title: "chapterName",
        namespace: "ruleToc",
        id: "chapterName",
        type: "String",
        hint: "Chọn tên chương (kết quả quy tắc là String)",
      },
      {
        title: "chapterUrl",
        namespace: "ruleToc",
        id: "chapterUrl",
        type: "String",
        hint: "Chọn link chương (kết quả của luật là một Url kiểu String)",
      },
      {
        title: "formatJs",
        namespace: "ruleToc",
        id: "formatJs",
        type: "String",
        hint: "Gọi lại để duyệt qua danh sách chương đã loại bỏ trùng lặp, cung cấp các biến chỉ mục (số chương bắt đầu từ 1), tiêu đề (tiêu đề chương), cung cấp thêm g int (giá trị ban đầu 0), trả về giá trị làm tiêu đề mới",
      },
      {
        title: "isVolume",
        namespace: "ruleToc",
        id: "isVolume",
        type: "String",
        hint: "Tên chương có phải là tên tập hay không (kết quả quy tắc là Bool)",
      },
      {
        title: "isVip",
        namespace: "ruleToc",
        id: "isVip",
        type: "String",
        hint: "章节是否为VIP章节 (规则结果为Bool)",
      },
      {
        title: "isPay",
        namespace: "ruleToc",
        id: "isPay",
        type: "String",
        hint: "Chương có được mua hay không (kết quả quy tắc là Bool)",
      },
      {
        title: "updateTime",
        namespace: "ruleToc",
        id: "updateTime",
        type: "String",
        hint: "Chọn thông tin chương (kết quả quy tắc là String)",
      },
      {
        title: "nextTocUrl",
        namespace: "ruleToc",
        id: "nextTocUrl",
        type: "String",
        hint: "Chọn liên kết trên trang tiếp theo của thư mục (kết quả của quy tắc là Danh sách<Chuỗi> hoặc Chuỗi)",
      },
    ],
  },
  content: {
    name: "nội dung",
    children: [
      {
        title: "webJs",
        namespace: "ruleContent",
        id: "webJs",
        type: "String",
        hint: "Inject javascript, được sử dụng để mô phỏng nhấp chuột, v.v., phải có giá trị trả về, thường là kiểu chuỗi",
      },
      {
        title: "content",
        namespace: "ruleContent",
        id: "content",
        type: "String",
        hint: "Chọn nội dung cơ thể (kết quả quy tắc là Chuỗi)",
      },
      {
        title: "title",
        namespace: "ruleContent",
        id: "title",
        type: "String",
        hint: "Kết quả tìm nạp sẽ ghi đè lên tiêu đề chương (quy tắc kết quả là Chuỗi)",
      },
      {
        title: "nextContentUrl",
        namespace: "ruleContent",
        id: "nextContentUrl",
        type: "String",
        hint: "Chọn liên kết trang tiếp theo (không phải chương tiếp theo) (kết quả của quy tắc là một Url kiểu String)",
      },
      {
        title: "sourceRegex",
        namespace: "ruleContent",
        id: "sourceRegex",
        type: "String",
        hint: "Khớp các đặc điểm url của tài nguyên để đánh hơi",
      },
      {
        title: "replaceRegex",
        namespace: "ruleContent",
        id: "replaceRegex",
        type: "String",
        hint: "Nội dung nhiều trang được hợp nhất và thay thế, được sử dụng để làm sạch văn bản",
      },
      {
        title: "imageStyle",
        namespace: "ruleContent",
        id: "imageStyle",
        type: "String",
        hint: "ĐẦY ĐỦ: Đã lát mà không tô: kiểu mặc định",
      },
      {
        title: "payAction",
        namespace: "ruleContent",
        id: "payAction",
        type: "String",
        hint: "Điền JavaScript để quay lại link mua hàng hoặc gọi giao diện mua hàng",
      },
      {
        title: "imageDecode",
        namespace: "ruleContent",
        id: "imageDecode",
        type: "String",
        hint: "Điền vào JavaScript để trả về các byte của hình ảnh được giải mã ",
      },
    ],
  },
  /*
  review: {
    name: "段评",
    children: [
      {
        title: "段评URL",
        namespace: "ruleReview",
id: "reviewUrl",
        type: "String",
        hint: "段评URL",
      },
      {
        title: "发布头像",
        namespace: "ruleReview",
id: "avatarRule",
        type: "String",
        hint: "段评发布者头像",
      },
      {
        title: "段评内容",
        namespace: "ruleReview",
id: "contentRule",
        type: "String",
        hint: "段评内容",
      },
      {
        title: "发布时间",
        namespace: "ruleReview",
id: "postTimeRule",
        type: "String",
        hint: "段评发布时间",
      },
      {
        title: "回复URL",
        namespace: "ruleReview",
id: "reviewQuoteUrl",
        type: "String",
        hint: "获取段评回复URL",
      },
      {
        title: "点赞URL",
        namespace: "ruleReview",
id: "voteUpUrl",
        type: "String",
        hint: "点赞URL",
      },
      {
        title: "点踩URL",
        namespace: "ruleReview",
id: "voteDownUrl",
        type: "String",
        hint: "点踩URL",
      },
      {
        title: "发送回复",
        namespace: "ruleReview",
id: "postReviewUrl",
        type: "String",
        hint: "发送回复URL",
      },
      {
        title: "回复段评",
        namespace: "ruleReview",
id: "postQuoteUrl",
        type: "String",
        hint: "发送回复段评URL",
      },
      {
        title: "删除段评",
        namespace: "ruleReview",
id: "deleteUrl",
        type: "String",
        hint: "删除段评URL",
      },
    ],
  },*/
  other: {
    name: "khác",
    children: [
      {
        title: "kích hoạt tìm kiếm",
        id: "enabled",
        type: "Boolean",
      },
      {
        title: "kích hoạt khám phá",
        id: "enabledExplore",
        type: "Boolean",
      },
      // {
      //   title: "启用段评",
      //   id: "enabledReview",
      //   type: "Boolean",
      // },
      {
        title: "Cookie",
        id: "enabledCookieJar",
        type: "Boolean",
      },
      {
        title: "trọng lượng tìm kiếm",
        id: "weight",
        type: "Number",
      },
      {
        title: "sắp xếp số",
        id: "customOrder",
        type: "Number",
      },
    ],
  },
};
